---
# Type Theme has documentation on these fields here:
# https://github.com/rohanchandra/type-theme

# Site configuration
url: "https://blog.lawrencejones.dev"
baseurl: ""

# Don't use the default /yyyy/mm/dd/title permalink to avoid breaking links when
# you change publish date.
permalink: /:categories/:title/

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Lawrence Jones
  avatar:
  favicon: assets/favicon.ico
  gravatar: a3d694b39e0e33fc479832b00dc128dc
  description: >
    Building reliable infrastructure for GoCardless, a fast-growing fintech
    based in London. Focused on tackling infrastructure problems with a software
    engineering mindset.

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
    Â© 2020 Lawrence Jones

  # Icons
  rss: true
  email_address: me@lawrencejones.dev
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: lawrencejones
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: lawrjones
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-134680924-1
  disqus_shortname:
  katex: false  # Enable if using math markup, but beware lighthouse
  search: false  # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Reload these by running:
  # make font-urls
  google_font_urls:
    - https://fonts.gstatic.com/s/sourcesanspro/v14/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDc.ttf
    - https://fonts.gstatic.com/s/sourcesanspro/v14/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZclSds18E.ttf
    - https://fonts.gstatic.com/s/sourcesanspro/v14/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7g.ttf
    - https://fonts.gstatic.com/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdr.ttf

  # Whenever we change font awesome version, we should check what font files are
  # loaded to update the list of preloads.
  font_awesome:
    href: https://use.fontawesome.com/releases/v5.8.2/css/all.css
    integrity: sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay
    preload_urls:
      - https://use.fontawesome.com/releases/v5.8.2/webfonts/fa-brands-400.woff2
      - https://use.fontawesome.com/releases/v5.8.2/webfonts/fa-solid-900.woff2

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock
